In [1]:
from netCDF4 import Dataset
import numpy as np
import matplotlib.pyplot as plt
import os

data_loc = "/home/hongshan/Dataset/SolarEnergy"
var = os.listdir(data_loc)[0]
dataset = Dataset(os.path.join(data_loc, var))
keys = dataset.dimensions.keys()

In [3]:
time = dataset.variables['time']
lat = dataset.variables['lat']
lon = dataset.variables['lon']
ens = dataset.variables['ens']
fhour = dataset.variables['fhour']

In [4]:
values = dataset.variables.values()
values_var = values[-1]
values_var = np.array(values_var)
values_var.shape

(5113, 11, 5, 9, 16)

In [17]:
a = lon.__array__()
b = lat.__array__()
c = time.__array__()


#print(np.scalar(np.where(a==256)))
print(a)
print(b)
print(c)

[ 254.  255.  256.  257.  258.  259.  260.  261.  262.  263.  264.  265.
  266.  267.  268.  269.]
[ 31.  32.  33.  34.  35.  36.  37.  38.  39.]
[ 1700568.  1700592.  1700616. ...,  1823208.  1823232.  1823256.]


In [63]:
def get_variable(var_path, time, lat, lon):
    # Arguments: indices of time, lat, lon
    # lat level: 9
    # lon level: 16
    # time level: 5113
    # Return: 5 measurements of the variable at the given lat, lon and time
    dataset = Dataset(var_path)
    values = dataset.variables.values()[-1]
    values = np.array(values)
    values = values.mean(axis=1) # take the mean of 11 emsemble of models
    return values[time,:,lat,lon].reshape(1, -1)

def group_variables(data_loc, time, lat, lon):
    # Arguments: 
    #    directory of all nc files
    #    fixed time
    #    fixed lat
    #    fixed lon
    # Return:
    #    numpy array of shape (5,15) 
    #    axis 0 means 5 measuresments, axis 1 means 15 variablesre
    all_vars = []
    for var in os.listdir(data_loc):
        var_path = os.path.join(data_loc, var)
        all_vars.append(get_variable(var_path, time, lat, lon))
        
    return np.concatenate(all_vars, axis=0).transpose()
    

In [64]:
group_variables(data_loc, time=0, lat=0, lon=0)

array([[  2.46765396e+02,   1.02251094e+05,   2.78509796e+02,
          0.00000000e+00,   4.01719287e-03,   5.68828392e+00,
          0.00000000e+00,   2.55516830e+02,   3.33394928e+02,
          0.00000000e+00,   2.75605682e+02,   2.80953400e+02,
          2.78494690e+02,   6.36363620e-05,   0.00000000e+00],
       [  2.38787094e+02,   1.02441000e+05,   2.77290802e+02,
          5.00000000e+00,   3.96183599e-03,   5.57272673e+00,
          0.00000000e+00,   2.50413559e+02,   3.24886108e+02,
          0.00000000e+00,   2.76441284e+02,   2.78463837e+02,
          2.78166748e+02,   6.36363620e-05,   1.00000000e+01],
       [  2.41719955e+02,   1.02374555e+05,   2.77292877e+02,
          5.90000000e+01,   3.85650783e-03,   5.97898149e+00,
          0.00000000e+00,   2.54760254e+02,   3.47171570e+02,
          0.00000000e+00,   2.90654022e+02,   2.83182312e+02,
          2.83206421e+02,   1.18181815e-04,   2.10000000e+02],
       [  2.61832245e+02,   1.02046875e+05,   2.83306061e+02,
     

In [19]:





# load all nc files into ram
# get all the values
def load_data(data_loc):
    variables = []
    for var in os.listdir(data_loc):
        var_path = os.path.join(data_loc, var)
        data = Dataset(var_path)
        dataset = Dataset(var_path)
        values = dataset.variables.values()[-1]
        values = np.array(values)
        values = values.mean(axis=1) # take mean of emsemble of models
        variables.append(values)
    return variables

all_variables = load_data(data_loc)

In [20]:
def check_index(latt, longi):
    lat_idx = np.where(lat.__array__() == latt)
    lon_idx = np.where(lon.__array__() == longi)
    return lat_idx, lon_idx
    
    

def get_variable(var, time, lat, lon):
    # Arguments: indices of time, lat, lon
    # lat level: 9
    # lon level: 16
    # time level: 5113
    # Return: 5 measurements of the variable at the given lat, lon and time
    # take the mean of 11 emsemble of models
    lat_idx, lon_idx = check_index(lat, lon)
    return var[time,:,lat_idx,lon_idx].reshape(1, -1)

def group_variables(list_of_variables, time, lat, lon):
    # Arguments: 
    #    directory of all nc files
    #    fixed time
    #    fixed lat
    #    fixed lon
    # Return:
    #    numpy array of shape (5,15) 
    #    axis 0 means 5 measuresments, axis 1 means 15 variablesre
    all_vars = []
    for var in list_of_variables:
        all_vars.append(get_variable(var, time, lat, lon))
        
    return np.concatenate(all_vars, axis=0).transpose()

In [21]:
get_variable(all_variables[0], time=0, lat=32, lon=254)

array([[ 234.31085205,  223.33256531,  226.90176392,  248.01405334,
         249.46836853]], dtype=float32)